### ISSUE TITLE
How to connect vectical left-right

### ISSUE THREAD

**Issue by geotyper** [action-script/ofxWFC3D#4]
Hello again,
can you be so please, to explain next line of XML
`<vertical left="turn" right="turn"/>`
As understand they lay above each other and dont have collision by side in vertical direction.
But what is vertical left and vertical right?
this is neighbor from up and down sides of cube, left this is up side of cube and right is down side upper cube? and when we rotate them (1,2,3) this counter clock rotation of cubes over axis Y? 
sorry for my english.

**Comment by action-script** [comment]
The configuration is inherited from the original code. I implemented it on that way to make the XML files compatible with the original WFC and the C# 3D simple implemnetation by mxgmn.

WFC is not an standardized technique and each implementation is different.
At ofxWFC3D I modified the axis coordinates and the propagation tables logic to fit OpenFrameworks standards.

At vertical neighbors, there is not symmetry and the XML describes which tiles can be placed on top of others. Being **left = down** and **right = up**.

You can change this logic to suit your own requirements and use the up/down properties labels instead.

**Comment by action-script** [comment]
The symmetries and rotations works over the Y axis at this implementation for OF.
I don't remember the the rotation direction, but you can look it up is the code.

**Comment by geotyper** [comment]
Thanks!
